version: "2.19.1"
services:
    db:
        build: ./db
        ports: 
            - 3306:3306
        #Lanzamos comando para autenticaci칩n con contrase침a desde mysql
        command: --default-authentication-plugin=mysql_native_password 
        #Variables
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: kikso
            MYSQL_PASSWORD: 1234
        volumes:
            #sincronizaci칩n bbdd
            - ./db:/docker-entrypoint-initdb.d
        networks:
            - default
    www:
        build: ./web
        ports: 
            - 8081:80
        volumes:
            - ./public:/var/www/html
        links:
            - db
        #red de conexi칩n de los contenedores
        networks:
            - default
    phpmyadmin:
        build: ./php
        links: 
            - db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: kikso
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: db
